- job:
    name: heat-functional-convg-queens
    parent: heat-functional-convg-mysql-lbaasv2
    nodeset: legacy-ubuntu-xenial
    override-checkout: stable/queens
    vars:
      branch_override: stable/queens

- job:
    name: heat-functional-orig-queens
    parent: heat-functional-orig-mysql-lbaasv2
    override-checkout: stable/queens
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/queens

- job:
    name: heat-functional-convg-rocky
    parent: heat-functional-convg-mysql-lbaasv2
    override-checkout: stable/rocky
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/rocky

- job:
    name: heat-functional-orig-rocky
    parent: heat-functional-orig-mysql-lbaasv2
    override-checkout: stable/rocky
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/rocky

- job:
    name: heat-functional-convg-stein
    parent: heat-functional-convg-mysql-lbaasv2
    override-checkout: stable/stein
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/stein

- job:
    name: heat-functional-orig-stein
    parent: heat-functional-orig-mysql-lbaasv2
    override-checkout: stable/stein
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/stein

- job:
    name: heat-functional-convg-train
    parent: heat-functional-convg-mysql-lbaasv2
    override-checkout: stable/train
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/train

- job:
    name: heat-functional-orig-train
    parent: heat-functional-orig-mysql-lbaasv2
    override-checkout: stable/train
    nodeset: legacy-ubuntu-xenial
    vars:
      branch_override: stable/train

- project:
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - heat-functional
        - heat-functional-non-apache
        - heat-functional-legacy
        - heat-functional-convg-queens
        - heat-functional-orig-queens
        - heat-functional-convg-rocky
        - heat-functional-orig-rocky
        - heat-functional-convg-stein
        - heat-functional-orig-stein
        - heat-functional-convg-train
        - heat-functional-orig-train
    gate:
      queue: heat
      jobs:
        - heat-functional
        - heat-functional-legacy
