- job:
    name: heat-functional-2024-2
    parent: heat-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- job:
    name: heat-functional-2024-1
    parent: heat-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1

- job:
    name: heat-functional-2023-2
    parent: heat-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2

- project:
    queue: heat
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - heat-functional
        - heat-functional-legacy
        - heat-functional-2024-2
        - heat-functional-2024-1
        - heat-functional-2023-2
    gate:
      jobs:
        - heat-functional
        - heat-functional-legacy
