- job:
    name: heat-functional-2023-1
    parent: heat-functional
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.1

- job:
    name: heat-functional-zed
    parent: heat-functional
    nodeset: openstack-single-node-focal
    override-checkout: stable/zed

- job:
    name: heat-functional-yoga
    parent: heat-functional
    nodeset: openstack-single-node-focal
    override-checkout: stable/yoga

- project:
    queue: heat
    templates:
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - heat-functional
        - heat-functional-legacy
        - heat-functional-2023-1
        - heat-functional-zed
        - heat-functional-yoga
    gate:
      jobs:
        - heat-functional
        - heat-functional-legacy
